---
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build
      - name: Build the file
        run: |
          yarn install
          yarn run build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.4.0

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/frigate-hass-card.js
          asset_name: frigate-hass-card.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: HACS release validation
        uses: "hacs/action@21.12.1"
        with:
          category: "plugin"
